image: Ubuntu  # образ для сборки

stack: jdk 11.0.24.8-hotspot  # версия JDK

branches:
  only:
    - main  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  # запускаем SUT (& означает, что в фоновом режиме не блокируем терминал для запуска тестов)
  - java -jar ./artifacts/app-replan-delivery.jar &

build_script:
  - chmod +x gradlew
  - ./gradlew test -Dselenide.headless=true --info